package com.adibrata.smartdealer.model;

// Generated Jul 5, 2015 7:32:33 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetMaster generated by hbm2java
 */
@Entity
@Table(name = "AssetMaster", schema = "dbo", catalog = "SmartDealer")
public class AssetMaster implements java.io.Serializable {

	private long id;
	private Partner partner;
	private String assetType;
	private String assetBrand;
	private String assetModel;
	private String assetCode;
	private Integer assetLevel;
	private Date dtmUpd;
	private String usrUpd;
	private Date dtmCrt;
	private String usrCrt;
	private Set<PurchaseOrderDtl> purchaseOrderDtls = new HashSet<PurchaseOrderDtl>(
			0);
	private Set<Stock> stocks = new HashSet<Stock>(0);

	public AssetMaster() {
	}

	public AssetMaster(long id) {
		this.id = id;
	}

	public AssetMaster(long id, Partner partner, String assetType,
			String assetBrand, String assetModel, String assetCode,
			Integer assetLevel, Date dtmUpd, String usrUpd, Date dtmCrt,
			String usrCrt, Set<PurchaseOrderDtl> purchaseOrderDtls,
			Set<Stock> stocks) {
		this.id = id;
		this.partner = partner;
		this.assetType = assetType;
		this.assetBrand = assetBrand;
		this.assetModel = assetModel;
		this.assetCode = assetCode;
		this.assetLevel = assetLevel;
		this.dtmUpd = dtmUpd;
		this.usrUpd = usrUpd;
		this.dtmCrt = dtmCrt;
		this.usrCrt = usrCrt;
		this.purchaseOrderDtls = purchaseOrderDtls;
		this.stocks = stocks;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PartnerCode")
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@Column(name = "AssetType", length = 20)
	public String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	@Column(name = "AssetBrand", length = 20)
	public String getAssetBrand() {
		return this.assetBrand;
	}

	public void setAssetBrand(String assetBrand) {
		this.assetBrand = assetBrand;
	}

	@Column(name = "AssetModel", length = 20)
	public String getAssetModel() {
		return this.assetModel;
	}

	public void setAssetModel(String assetModel) {
		this.assetModel = assetModel;
	}

	@Column(name = "AssetCode", length = 200)
	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	@Column(name = "AssetLevel")
	public Integer getAssetLevel() {
		return this.assetLevel;
	}

	public void setAssetLevel(Integer assetLevel) {
		this.assetLevel = assetLevel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmUpd", length = 16)
	public Date getDtmUpd() {
		return this.dtmUpd;
	}

	public void setDtmUpd(Date dtmUpd) {
		this.dtmUpd = dtmUpd;
	}

	@Column(name = "UsrUpd", length = 50)
	public String getUsrUpd() {
		return this.usrUpd;
	}

	public void setUsrUpd(String usrUpd) {
		this.usrUpd = usrUpd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmCrt", length = 16)
	public Date getDtmCrt() {
		return this.dtmCrt;
	}

	public void setDtmCrt(Date dtmCrt) {
		this.dtmCrt = dtmCrt;
	}

	@Column(name = "UsrCrt", length = 50)
	public String getUsrCrt() {
		return this.usrCrt;
	}

	public void setUsrCrt(String usrCrt) {
		this.usrCrt = usrCrt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assetMaster")
	public Set<PurchaseOrderDtl> getPurchaseOrderDtls() {
		return this.purchaseOrderDtls;
	}

	public void setPurchaseOrderDtls(Set<PurchaseOrderDtl> purchaseOrderDtls) {
		this.purchaseOrderDtls = purchaseOrderDtls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assetMaster")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

}
