package com.adibrata.smartdealer.model;

// Generated Jul 10, 2015 3:33:50 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrxConfigDtl generated by hbm2java
 */
@Entity
@Table(name = "TrxConfigDtl", schema = "dbo", catalog = "SmartDealer")
public class TrxConfigDtl implements java.io.Serializable {

	private long id;
	private TrxConfigHdr trxConfigHdr;
	private Long sequenceNo;
	private String coaName;
	private String coaSourceTable;
	private Character isCoaHeader;
	private Character post;
	private Character isMultipleDtl;
	private String tblSourceDtl;
	private String colSourceDtl;
	private String colFilterDtlId;
	private Character isCreatePaymentHistoryDetail;
	private Character isCreateCashBankMutationDetail;
	private Character isCreateJournalDetail;
	private Long departId;
	private String usrCrt;
	private Date dtmCrt;
	private String usrUpd;
	private Date dtmUpd;

	public TrxConfigDtl() {
	}

	public TrxConfigDtl(long id) {
		this.id = id;
	}

	public TrxConfigDtl(long id, TrxConfigHdr trxConfigHdr, Long sequenceNo,
			String coaName, String coaSourceTable, Character isCoaHeader,
			Character post, Character isMultipleDtl, String tblSourceDtl,
			String colSourceDtl, String colFilterDtlId,
			Character isCreatePaymentHistoryDetail,
			Character isCreateCashBankMutationDetail,
			Character isCreateJournalDetail, Long departId, String usrCrt,
			Date dtmCrt, String usrUpd, Date dtmUpd) {
		this.id = id;
		this.trxConfigHdr = trxConfigHdr;
		this.sequenceNo = sequenceNo;
		this.coaName = coaName;
		this.coaSourceTable = coaSourceTable;
		this.isCoaHeader = isCoaHeader;
		this.post = post;
		this.isMultipleDtl = isMultipleDtl;
		this.tblSourceDtl = tblSourceDtl;
		this.colSourceDtl = colSourceDtl;
		this.colFilterDtlId = colFilterDtlId;
		this.isCreatePaymentHistoryDetail = isCreatePaymentHistoryDetail;
		this.isCreateCashBankMutationDetail = isCreateCashBankMutationDetail;
		this.isCreateJournalDetail = isCreateJournalDetail;
		this.departId = departId;
		this.usrCrt = usrCrt;
		this.dtmCrt = dtmCrt;
		this.usrUpd = usrUpd;
		this.dtmUpd = dtmUpd;
	}

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TrxConfigHdrID")
	public TrxConfigHdr getTrxConfigHdr() {
		return this.trxConfigHdr;
	}

	public void setTrxConfigHdr(TrxConfigHdr trxConfigHdr) {
		this.trxConfigHdr = trxConfigHdr;
	}

	@Column(name = "SequenceNo")
	public Long getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(Long sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	@Column(name = "CoaName", length = 50)
	public String getCoaName() {
		return this.coaName;
	}

	public void setCoaName(String coaName) {
		this.coaName = coaName;
	}

	@Column(name = "CoaSourceTable", length = 50)
	public String getCoaSourceTable() {
		return this.coaSourceTable;
	}

	public void setCoaSourceTable(String coaSourceTable) {
		this.coaSourceTable = coaSourceTable;
	}

	@Column(name = "IsCoaHeader", length = 1)
	public Character getIsCoaHeader() {
		return this.isCoaHeader;
	}

	public void setIsCoaHeader(Character isCoaHeader) {
		this.isCoaHeader = isCoaHeader;
	}

	@Column(name = "Post", length = 1)
	public Character getPost() {
		return this.post;
	}

	public void setPost(Character post) {
		this.post = post;
	}

	@Column(name = "IsMultipleDtl", length = 1)
	public Character getIsMultipleDtl() {
		return this.isMultipleDtl;
	}

	public void setIsMultipleDtl(Character isMultipleDtl) {
		this.isMultipleDtl = isMultipleDtl;
	}

	@Column(name = "TblSourceDtl", length = 50)
	public String getTblSourceDtl() {
		return this.tblSourceDtl;
	}

	public void setTblSourceDtl(String tblSourceDtl) {
		this.tblSourceDtl = tblSourceDtl;
	}

	@Column(name = "ColSourceDtl", length = 50)
	public String getColSourceDtl() {
		return this.colSourceDtl;
	}

	public void setColSourceDtl(String colSourceDtl) {
		this.colSourceDtl = colSourceDtl;
	}

	@Column(name = "ColFilterDtlID", length = 50)
	public String getColFilterDtlId() {
		return this.colFilterDtlId;
	}

	public void setColFilterDtlId(String colFilterDtlId) {
		this.colFilterDtlId = colFilterDtlId;
	}

	@Column(name = "IsCreatePaymentHistoryDetail", length = 1)
	public Character getIsCreatePaymentHistoryDetail() {
		return this.isCreatePaymentHistoryDetail;
	}

	public void setIsCreatePaymentHistoryDetail(
			Character isCreatePaymentHistoryDetail) {
		this.isCreatePaymentHistoryDetail = isCreatePaymentHistoryDetail;
	}

	@Column(name = "IsCreateCashBankMutationDetail", length = 1)
	public Character getIsCreateCashBankMutationDetail() {
		return this.isCreateCashBankMutationDetail;
	}

	public void setIsCreateCashBankMutationDetail(
			Character isCreateCashBankMutationDetail) {
		this.isCreateCashBankMutationDetail = isCreateCashBankMutationDetail;
	}

	@Column(name = "IsCreateJournalDetail", length = 1)
	public Character getIsCreateJournalDetail() {
		return this.isCreateJournalDetail;
	}

	public void setIsCreateJournalDetail(Character isCreateJournalDetail) {
		this.isCreateJournalDetail = isCreateJournalDetail;
	}

	@Column(name = "DepartID")
	public Long getDepartId() {
		return this.departId;
	}

	public void setDepartId(Long departId) {
		this.departId = departId;
	}

	@Column(name = "UsrCrt", length = 50)
	public String getUsrCrt() {
		return this.usrCrt;
	}

	public void setUsrCrt(String usrCrt) {
		this.usrCrt = usrCrt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmCrt", length = 16)
	public Date getDtmCrt() {
		return this.dtmCrt;
	}

	public void setDtmCrt(Date dtmCrt) {
		this.dtmCrt = dtmCrt;
	}

	@Column(name = "UsrUpd", length = 50)
	public String getUsrUpd() {
		return this.usrUpd;
	}

	public void setUsrUpd(String usrUpd) {
		this.usrUpd = usrUpd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmUpd", length = 16)
	public Date getDtmUpd() {
		return this.dtmUpd;
	}

	public void setDtmUpd(Date dtmUpd) {
		this.dtmUpd = dtmUpd;
	}

}
